version: "3.8"

services:
  db:
    ports:
      - "127.0.0.1:15433:5432"

  mqtt:
    ports:
      - "127.0.0.1:11883:1883"

  nodered:
    ports:
      - "127.0.0.1:11880:1880"
    volumes:
      - ./nodered/data:/data

  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/var/www/html
    ports:
      - "127.0.0.1:18000:80"

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "127.0.0.1:13000:3000"

  nginx:
    ports:
      - "127.0.0.1:18080:80"
      - "127.0.0.1:18443:443"
